spring.application.name=Capgi_Boot_one
server.port=8083
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=PandaDb
spring.datasource.password=pandaDb

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=
